services:
  db:
    image: mariadb:10.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PWD}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - nextcloud_main:/var/www/html
      # 將外接硬碟綁定給 Nextcloud 的核心設定
      - /mnt/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PWD}

  collabora:
    image: collabora/code:latest
    container_name: collabora_server
    restart: always
    ports:
      - "9980:9980"
    environment:
      # 告訴 Collabora 允許哪個網域/IP 的 Nextcloud 來連線 (使用你目前的區網 IP)
      - aliasgroup1=http://172.20.10.3:8080
      # 關鍵設定：因為是區網內 HTTP 直連，必須關閉 SSL
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    cap_add:
      - MKNOD
      
volumes:
  db_data:
  nextcloud_main: