services:
  db:
    image: mariadb:10.11
    restart: always
    # 針對 2GB RAM 的資料庫記憶體優化限制
    command:
      - --transaction-isolation=READ-COMMITTED
      - --log-bin=binlog
      - --binlog-format=ROW
      - --innodb_buffer_pool_size=64M
      - --max_connections=50
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PWD}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - nextcloud_main:/var/www/html
      # 您的外接硬碟掛載點，直接對應 Nextcloud 的資料夾
      - /mnt/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${DB_PWD} # 必須跟上面一樣
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      # 限制 Nextcloud (PHP) 的最大記憶體使用量，防止系統崩潰
      - PHP_MEMORY_LIMIT=512M

  collabora:
    image: collabora/code:latest
    container_name: collabora_server
    restart: always
    ports:
      - "9980:9980"
    environment:
      # 告訴 Collabora 允許哪個網域/IP 的 Nextcloud 來連線
      - aliasgroup1=http://172.20.10.3:8080
      # 關鍵設定：因為是區網內 HTTP 直連，必須關閉 SSL
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
    cap_add:
      - MKNOD

volumes:
  db_data:
  nextcloud_main: